const {JSDOM,VirtualConsole}=require("jsdom");const fs=require("fs");
const html=fs.readFileSync(process.argv[2],"utf8");const REQUIRE_NAMES_HIDDEN=process.argv[3]==="--names-hidden";const errors=[];
const vc=new VirtualConsole();vc.on("jsdomError",e=>errors.push(String(e.message)));vc.on("error",e=>errors.push(String(e)));
const dom=new JSDOM(html,{runScripts:"dangerously",virtualConsole:vc,url:"https://example.test/"});
const w=dom.window,d=w.document;const out={};
out.title=d.getElementById("title").textContent;
out.cards=d.querySelectorAll("#list .card").length;
out.detailHasSummary=/Summary/.test(d.getElementById("detail").textContent);
const q=d.getElementById("q");q.value="equinor";q.dispatchEvent(new w.Event("input"));out.afterSearch=d.querySelectorAll("#list .card").length;
q.value="923609016";q.dispatchEvent(new w.Event("input"));out.afterOrgSearch=d.querySelectorAll("#list .card").length;
q.value="zzzz";q.dispatchEvent(new w.Event("input"));out.noMatchMsg=/No company matches/.test(d.getElementById("list").textContent);
q.value="";q.dispatchEvent(new w.Event("input"));
const f=d.getElementById("f");f.value="nosite";f.dispatchEvent(new w.Event("change"));out.nosite=d.querySelectorAll("#list .card").length;f.value="all";f.dispatchEvent(new w.Event("change"));
const cbs=d.querySelectorAll("#list input[type=checkbox]");cbs[0].checked=true;cbs[0].dispatchEvent(new w.Event("change"));cbs[1].checked=true;cbs[1].dispatchEvent(new w.Event("change"));
out.cmpLabel=d.getElementById("cmpbtn").textContent;d.getElementById("cmpbtn").click();out.compareTable=d.querySelectorAll("#detail table").length;out.compareCols=d.querySelectorAll("#detail thead th").length;
d.querySelectorAll("#list button")[0].click();out.openName=d.querySelector("#detail h2").textContent;
out.hash=w.location.hash;out.sourceDetails=d.querySelectorAll("#detail details").length;
out.names=/Nordmann/.test(d.documentElement.innerHTML);out.extRefs=(html.match(/<(script|link|img)[^>]+(src|href)=["']https?:/gi)||[]).length;
out.unknownPanel=/Not published and why/.test(d.getElementById("detail").textContent);out.errors=errors;
console.log(JSON.stringify(out,null,1));
const bad=out.errors.length||out.cards===0||out.extRefs>0||!out.detailHasSummary||(REQUIRE_NAMES_HIDDEN&&out.names);
process.exit(bad?1:0);
